apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toofics-poi-map-app-dev
  annotations:
    argocd/app-name: toofics-poi-map-app-dev
    backstage.io/kubernetes-id: toofics-poi-map-app
    backstage.io/kubernetes-namespace: toofics
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-vegas/toofics-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/dev-pipelines/ns/toofics/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/k8s/ns/toofics/deployments/toofics-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/#https://github.com/rhdh-vegas/toofics-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://toofics-poi-map-app-toofics.apps.rosa-bvg5j.wov7.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/toofics"
  system: workshop-system-toofics
  consumesApis:
    - gateway-api-toofics
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-toofics
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/toofics"
